import {
  Activity,
  Brain,
  Shield,
  Users,
  DollarSign,
  Calendar,
  TrendingUp,
  Zap,
} from "lucide-react";
import type { AgentCardProps } from "@/components/AgentCard";
import type { DecisionLogItemProps } from "@/components/DecisionLogItem";
import type { PredictionCardProps } from "@/components/PredictionCard";

export const AGENTS: AgentCardProps[] = [
  {
    id: "orchestrator",
    name: "Master Orchestrator",
    icon: Brain,
    status: "active",
    activeTasks: 8,
    recentActivity: "Coordinating preventive maintenance workflow across 3 agents. Resolving resource allocation conflict.",
    uptime: "99.9%",
    decisionsPerHour: 42,
    accuracy: 94,
    color: "bg-agent-orchestrator",
    onViewDetails: () => console.log("View Orchestrator details"),
  },
  {
    id: "monitoring",
    name: "Predictive Monitoring",
    icon: Activity,
    status: "processing",
    activeTasks: 12,
    recentActivity: "Analyzing metrics for 47 systems. Predicted disk failure in DB-Server-03 within 36 hours.",
    uptime: "99.8%",
    decisionsPerHour: 24,
    accuracy: 87,
    color: "bg-agent-monitoring",
    onViewDetails: () => console.log("View Monitoring details"),
  },
  {
    id: "decision",
    name: "Autonomous Decision",
    icon: Zap,
    status: "active",
    activeTasks: 6,
    recentActivity: "Auto-approved $1,200 preventive maintenance. Calculated ROI: 15:1. Initiated execution workflow.",
    uptime: "99.7%",
    decisionsPerHour: 18,
    accuracy: 92,
    color: "bg-agent-decision",
    onViewDetails: () => console.log("View Decision details"),
  },
  {
    id: "lifecycle",
    name: "Client Lifecycle",
    icon: Users,
    status: "active",
    activeTasks: 4,
    recentActivity: "Automated onboarding for new client 'TechCorp Inc'. Health score calculated: 87/100.",
    uptime: "99.6%",
    decisionsPerHour: 8,
    accuracy: 89,
    color: "bg-agent-lifecycle",
    onViewDetails: () => console.log("View Lifecycle details"),
  },
  {
    id: "resource",
    name: "Resource Optimization",
    icon: Calendar,
    status: "idle",
    activeTasks: 2,
    recentActivity: "Assigned technician Sarah Chen to critical ticket. Optimized maintenance window for minimal impact.",
    uptime: "99.5%",
    decisionsPerHour: 14,
    accuracy: 86,
    color: "bg-agent-resource",
    onViewDetails: () => console.log("View Resource details"),
  },
  {
    id: "financial",
    name: "Financial Intelligence",
    icon: DollarSign,
    status: "active",
    activeTasks: 5,
    recentActivity: "Updated profitability forecast. Detected $45K revenue opportunity with client expansion.",
    uptime: "99.8%",
    decisionsPerHour: 12,
    accuracy: 91,
    color: "bg-agent-financial",
    onViewDetails: () => console.log("View Financial details"),
  },
  {
    id: "security",
    name: "Security & Compliance",
    icon: Shield,
    status: "processing",
    activeTasks: 7,
    recentActivity: "Remediated 3 vulnerabilities automatically. Generated SOC2 compliance report.",
    uptime: "99.9%",
    decisionsPerHour: 16,
    accuracy: 95,
    color: "bg-agent-security",
    onViewDetails: () => console.log("View Security details"),
  },
  {
    id: "learning",
    name: "Learning & Adaptation",
    icon: TrendingUp,
    status: "active",
    activeTasks: 3,
    recentActivity: "Updated prediction models. Improved accuracy by +2.1% this week. Cross-agent insights applied.",
    uptime: "99.7%",
    decisionsPerHour: 6,
    accuracy: 88,
    color: "bg-agent-learning",
    onViewDetails: () => console.log("View Learning details"),
  },
];

export const RECENT_DECISIONS: DecisionLogItemProps[] = [
  {
    id: "dec-1",
    timestamp: "14:23:45",
    agentName: "Predictive Monitoring",
    agentIcon: Activity,
    agentColor: "bg-agent-monitoring",
    decisionType: "Preventive Maintenance Scheduled",
    description: "DB-Server-03: Predicted disk failure in 36hrs. Auto-scheduled replacement during maintenance window.",
    cost: 800,
    roi: 15,
    autonomyLevel: 1,
    autoApproved: true,
  },
  {
    id: "dec-2",
    timestamp: "14:18:12",
    agentName: "Security & Compliance",
    agentIcon: Shield,
    agentColor: "bg-agent-security",
    decisionType: "Vulnerability Auto-Remediation",
    description: "Patched CVE-2024-1234 across 12 servers. Low-risk update applied during approved hours.",
    cost: 0,
    roi: 999,
    autonomyLevel: 1,
    autoApproved: true,
  },
  {
    id: "dec-3",
    timestamp: "14:05:33",
    agentName: "Resource Optimization",
    agentIcon: Calendar,
    agentColor: "bg-agent-resource",
    decisionType: "Technician Assignment",
    description: "Critical ticket assigned to Sarah Chen based on skill match (98%) and availability.",
    cost: 0,
    roi: 0,
    autonomyLevel: 1,
    autoApproved: true,
  },
  {
    id: "dec-4",
    timestamp: "13:52:08",
    agentName: "Financial Intelligence",
    agentIcon: DollarSign,
    agentColor: "bg-agent-financial",
    decisionType: "Pricing Adjustment",
    description: "Adjusted Cloud Storage tier pricing +3.5% based on cost analysis. Within approved threshold.",
    cost: 0,
    roi: 8,
    autonomyLevel: 1,
    autoApproved: true,
  },
  {
    id: "dec-5",
    timestamp: "13:41:20",
    agentName: "Autonomous Decision",
    agentIcon: Zap,
    agentColor: "bg-agent-decision",
    decisionType: "Service Upgrade Approved",
    description: "Client 'Acme Corp' backup upgrade to hourly. Cost increase $450/mo. ROI calculated at 12:1.",
    cost: 5400,
    roi: 12,
    autonomyLevel: 2,
    autoApproved: true,
  },
];

export const PREDICTIONS: PredictionCardProps[] = [
  {
    id: "pred-1",
    title: "DB Server Disk Failure",
    description: "DB-Server-03 showing abnormal I/O patterns. SMART data indicates imminent disk failure.",
    severity: "critical",
    confidence: 87,
    timeToFailure: "36 hours",
    estimatedImpact: 12000,
    scheduledAction: "Replace disk, migrate data",
    scheduledTime: "Tomorrow at 2:00 AM PST",
  },
  {
    id: "pred-2",
    title: "Network Capacity Threshold",
    description: "Network-Switch-07 approaching 85% capacity. Traffic growth trend indicates saturation in 48hrs.",
    severity: "high",
    confidence: 82,
    timeToFailure: "48 hours",
    estimatedImpact: 8500,
    scheduledAction: "Upgrade switch, redistribute load",
    scheduledTime: "Friday at 11:00 PM PST",
  },
  {
    id: "pred-3",
    title: "License Expiration Risk",
    description: "Software licenses for 'Client-XYZ' expiring. Usage patterns suggest business disruption if not renewed.",
    severity: "medium",
    confidence: 95,
    timeToFailure: "14 days",
    estimatedImpact: 3200,
    scheduledAction: "Auto-renew licenses, notify client",
    scheduledTime: "Next Monday at 9:00 AM PST",
  },
];
